### PR TITLE
framework changes to support changing screen and loading image

### PR DESCRIPTION
**Pull request by ace90210**

### CODE REVIEW

**Comment by MiniAl** [comment]
This doesn't build; even after I solve the conflicts. It makes references to the class `android.support.v7.app.AppCompatActivity`, and a package `com.example.barry` (something you mocked up for testing?)

`AppCompatActivity` seems to be part of [the Android support library][2]. Have you changed the Android manifest and just not included it here? I added `compile "com.android.support:appcompat-v7:19.1.0"` to our 'mother/build.gradle' but Android Studio still complains that it is unable to resolve `AppCompatActivity`.

   [1]: http://developer.android.com/tools/support-library/

**Comment by MiniAl** [comment]
You can use `git pull --rebase [options] [<repository> [<refspec>…​]]` when you sync to dump your work at the end of the branch.

**Comment by ace90210** [comment]
Finally got this to load, I have just checked in a fix on my development branch on my fork.

i was relying on a reference to an auto generated package made externally hence this would never work outside my testing code, i have changed it to take the needed data as arguments and updated my test code to reflect this.

**Comment by ace90210** [comment]
Finally got this to load, I have just checked in a fix on my development branch on my fork.

i was relying on a reference to an auto generated package made externally hence this would never work outside my testing code, i have changed it to take the needed data as arguments and updated my test code to reflect this.

**Comment by MiniAl** [comment]
Unfortunately I've had to cherry pick these commits to avoid the merge but this work has been added and pushed.

When you're syncing up next time use `git pull --rebase [options] [<repository> [<refspec>…​]]`. It'll take your local history and apply it to the end of the work that's already in the repo.

**Pull request closed without merging**
